#!/bin/bash

if [[ -z "$1" || -z "$2" ]]; then
	echo "ERROR: need two dates to compare"
	exit 1
fi

date1AsNum=$(get-date-as-number -f "yyyy-mm-dd" $1)
date2AsNum=$(get-date-as-number -f "yyyy-mm-dd" $2)

if [[ "$date1AsNum" -lt "$date2AsNum" ]]; then
	echo "-1"
elif [[ "$date1AsNum" -gt "$date2AsNum" ]]; then
	echo "1";
else
	echo "0"
fi
