#!/bin/bash

tv_episode_regex="^(.+)[-_. ][sS]([0-9]{1,2})[eE]([0-9]{1,2}).*"
if [[ ! "$1" =~ $tv_episode_regex ]]; then
	echo "ERROR: Filename '$1' cannot be parsed as tv episode"
	exit 1
fi

series_name=$(echo "$1" | sed -r "s/$tv_episode_regex/\1/")
season_number=$(echo $1 | sed -r "s/$tv_episode_regex/\2/" | sed -r "s/^0?([0-9]+)/\1/")
formatted_season_num=$(printf "%02d\n" $season_number)
episode_number=$(echo $1 | sed -r "s/$tv_episode_regex/\3/" | sed "s/^0*//")
formatted_episode_num=$(printf "%02d\n" $episode_number)
formatted_series_name=$(echo "$series_name" | sed -r "s/([A-Z])/ \1/g" \
					 | sed -r "s/^ //g" \
					 | sed "s/[-._]//g" \
					 | sed -r "s/ ([ ]*)/ /g")
series_search_term=$(echo "$formatted_series_name" | sed -r "s/([A-Z])/\L\1/g")
extension="${1##*.}"

echo "{
\"filename\":\"$1\",
\"seriesId\":null,
\"seriesName\":\"$series_name\",
\"formattedSeriesName\":\"$formatted_series_name\",
\"seriesSearchTerm\":\"$series_search_term\",
\"seriesReleaseYear\":null,
\"seasonNumber\":$season_number,
\"formattedSeasonNum\":\"$formatted_season_num\",
\"episodeNumber\":$episode_number,
\"formattedEpisodeNum\":\"$formatted_episode_num\",
\"extension\":\"$extension\"
}"
