#!/bin/bash

tvEpisodeRegex="^(.+)[-_. ][sS]([0-9]{1,2})[eE]([0-9]{1,2}).*"
if [[ ! "$1" =~ $tvEpisodeRegex ]]; then
	echo "ERROR: Filename '$1' cannot be parsed as tv episode"
	exit 1
fi

seriesName=$(echo "$1" | sed -r "s/$tvEpisodeRegex/\1/")
seasonNumber=$(echo $1 | sed -r "s/$tvEpisodeRegex/\2/" | sed "s/^0*//")
formattedSeasonNum=$(printf "%02d\n" $seasonNumber)
episodeNumber=$(echo $1 | sed -r "s/$tvEpisodeRegex/\3/" | sed "s/^0*//")
formattedEpisodeNum=$(printf "%02d\n" $episodeNumber)
formattedSeriesName=$(echo "$seriesName" | sed -r "s/([A-Z])/ \1/g" \
										 | sed -r "s/^ //g" \
										 | sed "s/[-._]//g" \
										 | sed -r "s/ ([ ]*)/ /g")
seriesSearchTerm=$(echo "$formattedSeriesName" | sed -r "s/([A-Z])/\L\1/g")
extension="${1##*.}"

echo "{
\"filename\":\"$1\",
\"seriesId\":null,
\"seriesName\":\"$seriesName\",
\"formattedSeriesName\":\"$formattedSeriesName\",
\"seriesSearchTerm\":\"$seriesSearchTerm\",
\"seasonNumber\":$seasonNumber,
\"formattedSeasonNum\":\"$formattedSeasonNum\",
\"episodeNumber\":$episodeNumber,
\"formattedEpisodeNum\":\"$formattedEpisodeNum\",
\"extension\":\"$extension\"
}"
