#!/bin/bash

tvEpisodeRegex="^(.+)[-_. ][sS]([0-9]{1,2})[eE]([0-9]{1,2}).*"
if [[ ! "$1" =~ $tvEpisodeRegex ]]; then
	echo "ERROR: Filename '$1' cannot be parsed as tv episode"
	exit 1
fi

seriesName=$(echo "$1" | sed -r "s/$tvEpisodeRegex/\1/")
seasonNumber=$(echo $1 | sed -r "s/$tvEpisodeRegex/\2/" | sed "s/^0*//")
episodeNumber=$(echo $1 | sed -r "s/$tvEpisodeRegex/\3/" | sed "s/^0*//")
formattedSeriesName=$(echo "$seriesName" | sed -r "s/([A-Z])/ \1/g" \
										 | sed -r "s/^ //g" \
										 | sed "s/[-._]//g" \
										 | sed -r "s/ ([ ]*)/ /g")

echo "{\"filename\":\"$1\",\"seriesName\":\"$seriesName\",\"formattedSeriesName\":\"$formattedSeriesName\",\"seasonNumber\":$seasonNumber,\"episodeNumber\":$episodeNumber}"
