#!/bin/bash

MONTH_FROM_DATE_REGEX="^[0-9]{2}/([A-Za-z]{3,})/[0-9]{2,4}$"

month=$(sed -nr "s|$MONTH_FROM_DATE_REGEX|\1|p" <<< "$1")
monthAsNum=$(getMonthAsNumber $month)

DAY_MONTH_YEAR_FROM_DATE_REGEX="(.*)/([A-Za-z]{3,})/(.*)"
dateWithMonthAsNumber=$(sed -nr "s|$DAY_MONTH_YEAR_FROM_DATE_REGEX|\1${monthAsNum}\3|p" <<< "$1")
echo "$dateWithMonthAsNumber"
