#!/bin/bash

case $1 in
	Jan|January)
		echo "01";;
	Feb|February)
		echo "02";;
	Mar|March)
		echo "03";;
	Apr|April)
		echo "04";;
	May)
		echo "05";;
	Jun|June)
		echo "06";;
	Jul|July)
		echo "07";;
	Aug|August)
		echo "08";;
	Sep|September)
		echo "09";;
	Oct|October)
		echo "10";;
	Nov|November)
		echo "11";;
	Dec|December)
		echo "12";;
	*)
		echo "ERROR: Cannot parse month"
		exit $ERROR_UNABLE_TO_PARSE_MONTH
esac
