#!/bin/bash
set -euo pipefail
filename="$1"

if [[ -z "$filename" ]]; then
  echo "ERROR: No filename provided." >&2
  exit 1
fi

film_name=$(basename "${filename%.*}")
formatted_film_name=$(sed -r -e "s/([A-Z])/ \1/g" -e "s/^ //g" -e "s/[-._]//g" -e "s/ +/ /g" <<< "$film_name")
echo "$formatted_film_name"