#!/bin/bash

CACHED_TOKEN_FILE="/tmp/usr/.tvdb-token-cache"

if [[ -z $1 ]]; then
	echo "ERROR: no API key provided."
	exit 1
fi

if [[ -e "$CACHED_TOKEN_FILE" ]]; then
	secondsSinceTokenCacheUpdated=$(( $(date +%s) - $(date -r $CACHED_TOKEN_FILE +%s) ))
	if [[ $secondsSinceTokenCacheUpdated -lt "84000" ]]; then
		cat "$CACHED_TOKEN_FILE"
		exit 0
	fi
fi

loginUrl="https://api.thetvdb.com/login"
acceptJsonHeader="Accept: application/json"
jsonContentHeader="Content-Type: application/json"

rawJson=$(curl --silent -X POST --header "$acceptJsonHeader" --header "$jsonContentHeader" -d "{ \"apikey\":\"$1\" }" "$loginUrl")
token=$(echo "$rawJson" | jq -r ".token")

echo "$token" > "$CACHED_TOKEN_FILE"
echo "$token"
