#!/bin/bash
set -euo pipefail

CACHE_DIRECTORY="/tmp/usr/tvdb-cache"
MAIN_ARGS=()
use_cache=true

__parse_flags() {
	PARSED_OPTIONS=$(getopt -n "$0"  -o s: --long "skip-cache"  -- "$@")
	eval set -- "$PARSED_OPTIONS"

	while true;	do
		case "$1" in
			-s|--skip-cache)
				use_cache=false
				shift;;

			--)
				shift
				break;;
		esac
	done

	MAIN_ARGS=("$@")
}

__get_jq_episode_details_query() {
	local season_number="${1:-}"
	local episode_number="${2:-}"

	if [[ -n $season_number && -n $episode_number ]]; then
		echo "map(select(.season == $season_number and .episode == $episode_number)) | select(any) // null"
	elif [[ -n $season_number ]]; then
		echo "map(select(.season == $season_number)) | select(any) // null"
	else
		echo "select(any) // null"
	fi
}

__get_cached_episode_details() {
	local series_id="$1"
	local jq_query="$2"

	if [[ -e "$CACHE_DIRECTORY/.$series_id" ]]; then
		jq -c "$jq_query" "$CACHE_DIRECTORY/.$series_id"
	else
		echo "null"
	fi
}

__get_episode_details_page() {
	local token="$1"
	local series_id="$2"
	local page_number="$3"

	local episodes_details_json=$(tvdb-get-request $token "/series/$series_id/episodes/official?page=$page_number")
	jq -c '.' <<< "$episodes_details_json"
}

__get_episode_details() {
	local series_id="$1"

	local token=$(tvdb-authenticate $TVDB_API_KEY)

	local page_number=0
	local episode_details=[]
	while true; do
		local tvdb_episode_details=$(__get_episode_details_page "$token" "$series_id" "$page_number")
		local page_episode_details=$(jq -c '[.data.episodes[] | { season: .seasonNumber, episode: .number, name: .name}]' <<< "$tvdb_episode_details")
		episode_details=$(jq -c ". + $page_episode_details" <<< "$episode_details")

		if jq -e '.links.next == null' <<< "$tvdb_episode_details" > /dev/null; then
			jq -c '.' <<< "$episode_details"
			return
		else
			page_number=$((page_number + 1))
		fi
	done
}

__cache_episode_details() {
	local series_id="$1"
	local episode_details="$2"

	echo "$episode_details" > "$CACHE_DIRECTORY"/.$series_id
}

main() {
	__parse_flags "$@"
	set -- "${MAIN_ARGS[@]}"

	local series_id="${1:?ERROR - No series id provided.}"
	local season_number="${2:-}"
	local episode_number="${3:-}"

	mkdir -p "$CACHE_DIRECTORY"

	jq_episode_details_query=$(__get_jq_episode_details_query $season_number $episode_number)

	episode_details="null"
	if $use_cache; then
		episode_details=$(__get_cached_episode_details "$series_id" "$jq_episode_details_query")
	fi

	if [[ "$episode_details" != "null" ]]; then
		jq -c '.' <<< "$episode_details"
	else
		episode_details=$(__get_episode_details "$series_id")
		if $use_cache; then
			__cache_episode_details "$series_id" "$episode_details"
		fi
		jq -c "$jq_episode_details_query" <<< "$episode_details"
	fi

}

main "$@"