#!/bin/bash
set -euo pipefail

series_search_term="${1:?ERROR - No series search term provided.}"

token=$(tvdb-authenticate "$TVDB_API_KEY")
url_safe_series_name=$(urlencode "$series_search_term")
search_result_json=$(tvdb-get-request "$token" "/search?query=$url_safe_series_name&type=series&language=eng")

jq -cr 'if has("data") then [ .data[] | {name: .name, id: .tvdb_id, release_year: .year, overview: .overview}] else null end' <<< "$search_result_json"