#!/bin/bash

if [[ -z $1 ]]; then
  echo "ERROR: No series search term provided."
  exit 1
fi

token=$(tvdb-authenticate "$TVDB_API_KEY")

url_safe_series_name=$(urlencode "$1")
search_result_json=$(tvdb-get-request $token "/search/series?name='$url_safe_series_name'")

jq -cr 'if has("data") then [ .data[] | {seriesName: .seriesName, seriesId: .id, seriesReleaseYear: (.firstAired | split("-")[0])}] else null end' <<<$search_result_json
