#!/bin/bash
set -euo pipefail

CACHED_TOKEN_DIRECTORY="/tmp/usr/tvdb-cache"
CACHED_TOKEN_FILE="$CACHED_TOKEN_DIRECTORY/.tvdb-token-cache"

api_key="${1:?ERROR - No API token provided.}"

if [[ -e "$CACHED_TOKEN_FILE" ]]; then
	seconds_since_token_cache_updated=$(( $(date +%s) - $(date -r $CACHED_TOKEN_FILE +%s) ))
	if [[ $seconds_since_token_cache_updated -lt "84000" ]]; then
		cat "$CACHED_TOKEN_FILE"
		exit 0
	fi
fi

response=$(curl --silent -X POST --header "accept: application/json" --header "Content-Type: application/json" -d "{ \"apikey\": \"$api_key\" }" "https://api4.thetvdb.com/v4/login")

if jq -e '.status != "success"' <<< "$response" > /dev/null; then
	echo "ERROR - failure trying to authenticate. Message = '$(jq -r '.message' <<< "$response")'."
	exit 1
fi

token=$(jq -r '.data.token' <<< "$response")

mkdir -p "$CACHED_TOKEN_DIRECTORY"
(umask 077; echo "$token" > "$CACHED_TOKEN_FILE")

echo "$token"
