#!/bin/bash
set -euo pipefail

api_token="${1:?ERROR - No API token provided.}"
api_path="${2:?ERROR - No API request URL provided.}"

response=$(curl --silent -X GET --header "Accept: application/json" --header "Authorization: Bearer $api_token" "https://api4.thetvdb.com/v4$api_path")

if jq -e '.status != "success"' <<< "$response" > /dev/null; then
	echo "ERROR - Got failure response from TVDB. Message: $(jq -r '.message' <<< "$response")"
	exit 1
fi

echo "$response"